# Generated by Django 2.0 on 2018-01-17 22:10

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SlideDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryJson', jsonfield.fields.JSONField(default=dict)),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlideDB.Slide')),
            ],
        ),
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='searchquery',
            name='results',
            field=models.ManyToManyField(to='SlideSearch.SearchResult'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='SlideSearch.SearchSession'),
        ),
    ]
