# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 14:24
from __future__ import unicode_literals

import SlideDB.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='content',
            field=enumfields.fields.EnumField(default=0, enum=SlideDB.models.SlideContentChoices, max_length=10),
        ),
    ]
