# Generated by Django 2.0 on 2018-01-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
