# Generated by Django 2.0 on 2018-02-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0002_slide_zeptodownloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='visualStyle',
        ),
    ]
