# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 11:21
from __future__ import unicode_literals
from django.db import migrations
from django.core.files import File
from urllib.request import urlretrieve, urlcleanup


def populate_media_files(apps, schema_editor):
    """
    We can't import the Slide model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """

    Slide = apps.get_model('SlideDB', 'Slide')
    for slide in Slide.objects.all():
        # Define image file name
        image_name = slide.thumbnailFile.split("/")[-1]

        # Define pptx file name
        file_name = slide.pptFile.split("/")[-1]

        # Retrieve pptx file from url and save it into new file field.
        try:
            ppt_file, _ = urlretrieve(slide.pptFile)
            slide.pptxFile.save(file_name, File(open(ppt_file, 'rb')))
        finally:
            urlcleanup()

        # Retrieve image file from url and save it into new image field.
        try:
            image_file, _ = urlretrieve(slide.thumbnailFile)
            slide.imageFile.save(image_name, File(open(image_file, 'rb')))
        finally:
            urlcleanup()

        slide.save()


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0002_auto_20180507_0901'),
    ]

    operations = [
        migrations.RunPython(populate_media_files),
    ]
