# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0002_slide_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='imageFile',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='uploads/images/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='pptxFile',
            field=models.FileField(default='/static/pptx/default.pptx', upload_to='uploads/pptx/'),
        ),
    ]
