# Generated by Django 2.0 on 2018-01-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0002_slide_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
