# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 10:44
from __future__ import unicode_literals

import SlideDB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0003_auto_20180507_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='pptFile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='thumbnailFile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='zeptoDownloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slide',
            name='zeptoId',
            field=models.IntegerField(default=SlideDB.models.Slide.zeptoNum, unique=True),
        ),
    ]
