# Generated by Django 2.0 on 2018-01-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0003_auto_20180124_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='pptFile',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='slide',
            name='thumbnailFile',
            field=models.URLField(),
        ),
    ]
