# Generated by Django 2.0 on 2018-02-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlideDB', '0005_auto_20180130_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField()),
                ('zeptoId', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField()),
                ('zeptoId', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slidetype',
            name='parent',
        ),
        migrations.AddField(
            model_name='concept',
            name='zeptoId',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='SlideDB.Construct'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='zeptoId',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='SlideType',
        ),
        migrations.AddField(
            model_name='subconcept',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subConcepts', to='SlideDB.Concept'),
        ),
        migrations.AddField(
            model_name='construct',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructs', to='SlideDB.SubConcept'),
        ),
    ]
