# Generated by Django 2.0 on 2018-02-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Search', '0001_initial'),
        ('SlideDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlideDB.Slide'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='Search.SearchIndex'),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='rankingSources',
            field=models.ManyToManyField(blank=True, to='Search.SearchQuery'),
        ),
        migrations.AlterUniqueTogether(
            name='searchresultrating',
            unique_together={('user', 'result')},
        ),
    ]
