# Generated by Django 2.0 on 2018-01-21 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SlideDB', '0001_initial'),
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlideDB.Slide'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='results',
            field=models.ManyToManyField(to='Search.SearchResult'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='Search.SearchSession'),
        ),
    ]
