# Generated by Django 2.0 on 2018-02-24 05:47

import Search.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20180222_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='resultJson',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='searchindex',
            name='pickledModelFile',
            field=models.FileField(upload_to=Search.models.SearchIndex.pickFilename),
        ),
    ]
