# Generated by Django 2.0 on 2018-02-13 11:27

import Search.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20180213_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchindex',
            name='searchAlgo',
        ),
        migrations.AddField(
            model_name='searchindex',
            name='indexType',
            field=enumfields.fields.EnumField(default=1, enum=Search.models.IndexTypeChoices, max_length=10),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='rankingSources',
            field=models.ManyToManyField(to='Search.SearchIndex'),
        ),
    ]
