# Generated by Django 2.0 on 2018-02-26 13:18

import Search.models
import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20180224_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchindex',
            name='evalResults',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='downloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
