# Generated by Django 2.0 on 2018-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20180213_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='rankingSources',
            field=models.ManyToManyField(blank=True, to='Search.SearchIndex'),
        ),
    ]
