# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 11:01
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0004_auto_20180226_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='queryJson',
            field=jsonfield.fields.JSONCharField(default={'Keywords': []}, max_length=512),
        ),
    ]
