# Generated by Django 2.0 on 2018-02-14 09:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0004_auto_20180213_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='rating',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='queryJson',
            field=jsonfield.fields.JSONField(default={'Keywords': 'agenda'}),
        ),
    ]
