# Generated by Django 2.0 on 2018-02-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0005_auto_20180214_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='results',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Search.SearchQuery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchresultrating',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Search.SearchResult'),
        ),
    ]
