# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 13:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0005_auto_20180411_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='queryJson',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Keywords': []}),
        ),
    ]
