# Generated by Django 2.0 on 2018-02-16 19:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0006_auto_20180214_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ('rank',)},
        ),
        migrations.RenameField(
            model_name='searchresultrating',
            old_name='rating',
            new_name='rated',
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='queryJson',
            field=jsonfield.fields.JSONField(default={'Keywords': ['agenda']}),
        ),
    ]
