# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 06:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SlideDB', '0001_initial'),
        ('Search', '0006_auto_20180411_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryInvocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultJson', jsonfield.fields.JSONField(default=[])),
                ('created', models.DateTimeField(editable=False)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='Search.SearchIndex')),
            ],
        ),
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ('queryInvocation', 'rank')},
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='created',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='index',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='resultJson',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='query',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='downloads',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='searchresultrating',
            name='query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Search.SearchQuery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresultrating',
            name='slide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='SlideDB.Slide'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='searchresultrating',
            name='downloads',
        ),
        migrations.AlterUniqueTogether(
            name='searchresultrating',
            unique_together=set([('user', 'slide')]),
        ),
        migrations.RemoveField(
            model_name='searchresultrating',
            name='result',
        ),
        migrations.AddField(
            model_name='searchqueryinvocation',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='Search.SearchQuery'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='queryInvocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Search.SearchQueryInvocation'),
            preserve_default=False,
        ),
    ]
