# Generated by Django 2.0 on 2018-02-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0007_auto_20180217_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ('query', 'rank')},
        ),
        migrations.AddField(
            model_name='searchindex',
            name='pickledModelFile',
            field=models.FileField(default='', upload_to='searchIndices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchindex',
            name='rankingSources',
            field=models.ManyToManyField(blank=True, to='Search.SearchQuery'),
        ),
    ]
