# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 09:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0007_auto_20180417_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryJson', django.contrib.postgres.fields.jsonb.JSONField(default={'Keywords': []})),
            ],
        ),
        migrations.RemoveField(
            model_name='searchqueryinvocation',
            name='index',
        ),
        migrations.RemoveField(
            model_name='searchqueryinvocation',
            name='query',
        ),
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ('query', 'rank')},
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='queryJson',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='queryInvocation',
        ),
        migrations.RemoveField(
            model_name='searchresultrating',
            name='query',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchquery',
            name='index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='Search.SearchIndex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchquery',
            name='resultJson',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Search.SearchQuery'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SearchQueryInvocation',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='queryTemplate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='Search.SearchQueryTemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresultrating',
            name='queryTemplate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Search.SearchQueryTemplate'),
            preserve_default=False,
        ),
    ]
