# Generated by Django 2.0 on 2018-02-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0008_auto_20180221_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchindex',
            name='schemaVersion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
